# Generated by Django 6.0.3 on 2026-05-17 14:26

import app.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50, verbose_name='Exercise')),
                ('unit', models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', max_length=20, verbose_name='Unit')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), default=list)),
                ('requires_weight', models.BooleanField(default=False, verbose_name='Requires Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('added_hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Added Hashtags'), default=list)),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates')),
                ('public_visibility', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow Comments')),
                ('hide_likes', models.BooleanField(default=False, verbose_name='Hide Likes')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('latest_interaction', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Latest Interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reports', models.IntegerField(default=0, verbose_name='Reports')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.getPostUploadPath)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=app.models.getPostUploadPath)),
                ('is_video', models.BooleanField(default=False, verbose_name='Is Video')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Filename')),
                ('original_size', models.BigIntegerField(blank=True, null=True, verbose_name='Original Size')),
                ('compressed_size', models.BigIntegerField(blank=True, null=True, verbose_name='Compressed Size')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.post', verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('email_address', models.CharField(max_length=50, verbose_name='E-mail Address')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=20, verbose_name='Role')),
                ('profile_picture_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profile Picture File')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language Code')),
                ('last_edit', models.DateTimeField(blank=True, null=True, verbose_name='Last Edit Time')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code')),
                ('password_reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset Code')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID')),
                ('blog_subscribe', models.BooleanField(default=False, verbose_name='Blog Subscribe')),
                ('friend_code', models.CharField(max_length=6, verbose_name='Friend Code')),
                ('bio', models.TextField(blank=True, max_length=100, null=True, verbose_name='Bio')),
                ('xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('account_status', models.CharField(choices=[('unverified', 'unverified'), ('OK', 'OK'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='unverified', max_length=20, verbose_name='Account Status')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='app.users', verbose_name='Following')),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='saved_posts', to='app.post', verbose_name='Saved Posts')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe ID')),
                ('cardholder_name', models.CharField(max_length=50, verbose_name='Cardholder Name')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount (€)')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_plan_key', models.CharField(default='None', max_length=50, verbose_name='Training Plan Key')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='Day')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('exercise', models.CharField(max_length=50, verbose_name='Exercise')),
                ('periods', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Reps'), default=list)),
                ('unit', models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', max_length=20, verbose_name='Unit')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_plans', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SeenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_instances', to='app.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_instances', to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('review', models.TextField(max_length=200, null=True, verbose_name='Review')),
                ('last_edit', models.DateTimeField(blank=True, null=True, verbose_name='Last Edit Time')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', max_length=50, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', max_length=20, verbose_name='Status')),
                ('reports', models.IntegerField(default=0, verbose_name='Reports')),
                ('level', models.PositiveIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.postforum')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post', verbose_name='Post')),
                ('likes_from_users', models.ManyToManyField(blank=True, related_name='liked_post_forum_comments', to='app.users', verbose_name='Likes From Users')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='app.users', verbose_name='Likes From Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, related_name='reported_posts', through='app.PostReport', to='app.users', verbose_name='Reports From Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='seen_by',
            field=models.ManyToManyField(related_name='viewed_posts', through='app.SeenPost', to='app.users'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, to='app.users', verbose_name='Tagged Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.users', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), default=list)),
                ('rating', models.FloatField(default=0, verbose_name='Rating')),
                ('visitors', models.IntegerField(default=0, verbose_name='Visitors')),
                ('link', models.CharField(max_length=50, verbose_name='Link')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image File')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('likes_from_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Likes From Users'), default=list)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', max_length=20, verbose_name='Status')),
                ('reports', models.IntegerField(default=0, verbose_name='Reports')),
                ('reports_from_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Reports From Users'), default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.articleforum')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.articles', verbose_name='Article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.users', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='End Time')),
                ('formatted_elapsed_time', models.CharField(default='00h 00m 01s', max_length=11, verbose_name='Formatted Elapsed Time')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='Elapsed Time (Seconds)')),
                ('gained_xp', models.IntegerField(default=0, verbose_name='Gained XP')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('training_plan_day', models.IntegerField(blank=True, null=True, verbose_name='Day')),
                ('training_plan_summary', models.JSONField(blank=True, default=list, null=True, verbose_name='Training Plan Summary')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='app.users', verbose_name='User')),
            ],
        ),
    ]
