# Generated by Django 6.0.3 on 2026-05-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', max_length=50, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('postforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postforum', verbose_name='Post Forum Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('postforum', 'user')},
            },
        ),
        migrations.AddField(
            model_name='postforum',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, related_name='reported_post_forum_comments', through='app.PostForumReport', to='app.users', verbose_name='Reports From Users'),
        ),
    ]
