# Generated by Django 5.2.4 on 2025-10-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_swzilinausers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SWZilinaUsers',
            new_name='Users',
        ),
    ]
