# Generated by Django 6.0.3 on 2026-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postforumreport_postforum_reports_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
