# Generated by Django 5.2.4 on 2025-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_swzilinausers_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture_name',
            field=models.CharField(max_length=50, null=True, verbose_name='profile_picture_name'),
        ),
    ]
