# Generated by Django 6.0.3 on 2026-05-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reviews_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', max_length=50, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reviews', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.AddField(
            model_name='reviews',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, related_name='reported_reviews', through='app.ReviewReport', to='app.users', verbose_name='Reports From Users'),
        ),
    ]
