# Generated by Django 6.0.3 on 2026-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reviews_reports_reviewreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('data', models.CharField(max_length=100, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('data', models.CharField(max_length=100, verbose_name='Data')),
                ('xp', models.IntegerField(default=0, verbose_name='XP')),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('hidden', 'hidden')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
