# Generated by Django 6.0.3 on 2026-05-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customtasks_officialtasks_alter_reviews_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyOfficialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.officialtasks', verbose_name='Official Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.AddField(
            model_name='users',
            name='daily_official_tasks',
            field=models.ManyToManyField(blank=True, through='app.UserDailyOfficialTasks', to='app.officialtasks', verbose_name='Daily Official Tasks'),
        ),
    ]
