# Generated by Django 5.2.4 on 2025-10-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='profile_picture_name'),
        ),
    ]
