# Generated by Django 6.0.3 on 2026-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdailyofficialtasks_users_daily_official_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyofficialtasks',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is Done'),
        ),
    ]
