# Generated by Django 6.0.3 on 2026-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userdailyofficialtasks_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdailyofficialtasks',
            name='is_done',
        ),
        migrations.AddField(
            model_name='userdailyofficialtasks',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
    ]
