# Generated by Django 6.0.3 on 2026-05-24 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_userdailyofficialtasks_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customtasks',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AddField(
            model_name='customtasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
            preserve_default=False,
        ),
    ]
