# Generated by Django 6.0.3 on 2026-05-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customtasks_created_at_customtasks_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtasks',
            name='data',
        ),
    ]
