# Generated by Django 6.0.3 on 2026-05-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customtasks_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
