# Generated by Django 5.2.4 on 2025-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_users_creation_time_users_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Edit Time'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Edit Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profile Picture File'),
        ),
    ]
