# Generated by Django 5.2.4 on 2025-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reviews_last_edit_alter_reviews_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID'),
        ),
    ]
