# Generated by Django 6.0.3 on 2026-05-26 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_postmedia_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyofficialtasks',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Progress Percentage'),
        ),
    ]
