# Generated by Django 6.0.3 on 2026-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userdailyofficialtasks_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtasks',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
