# Generated by Django 5.2.4 on 2025-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset Code'),
        ),
    ]
