# Generated by Django 6.0.3 on 2026-05-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customtasks_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='formatted_elapsed_time',
        ),
    ]
