# Generated by Django 5.2.4 on 2025-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_users_password_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('visitors', models.IntegerField(default=0, verbose_name='Rating')),
            ],
        ),
    ]
