# Generated by Django 5.2.4 on 2025-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
