# Generated by Django 6.0.3 on 2026-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_activity_formatted_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='xp_boost_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='XP Boost Expiration Time'),
        ),
    ]
