# Generated by Django 6.0.3 on 2026-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_users_xp_boost_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='xp_boost_expiration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='XP Boost Expiration Time'),
        ),
    ]
