# Generated by Django 5.2.4 on 2025-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_articles_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(max_length=50, verbose_name='URL / Class'),
        ),
    ]
