# Generated by Django 6.0.3 on 2026-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_users_xp_boost_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_activities',
            field=models.IntegerField(default=0, verbose_name='Total Activities'),
        ),
    ]
