# Generated by Django 6.0.3 on 2026-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_users_total_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activity_streak',
            field=models.IntegerField(default=0, verbose_name='Activity Streak'),
        ),
    ]
