# Generated by Django 5.2.4 on 2025-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_articles_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='url',
        ),
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(default='url', max_length=50, null=True, verbose_name='Link'),
        ),
    ]
