# Generated by Django 6.0.3 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_users_activity_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_activity_streak_increase_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity Streak Increase Time'),
        ),
    ]
