# Generated by Django 6.0.3 on 2026-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_users_last_activity_streak_increase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='max_activity_streak',
            field=models.IntegerField(default=0, verbose_name='Max Activity Streak'),
        ),
    ]
