# Generated by Django 5.2.4 on 2025-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_articles_url_articles_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(max_length=50, verbose_name='Link'),
        ),
    ]
