# Generated by Django 6.0.3 on 2026-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_users_max_activity_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Level'),
        ),
    ]
