# Generated by Django 6.0.3 on 2026-06-01 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_users_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='level',
        ),
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Elapsed Time (Seconds)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gained_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Gained XP'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='training_plan_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='reports',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='visitors',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitors'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='officialtasks',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reports',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='reports',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reports',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name='Reps'), default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='activity_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Activity Streak'),
        ),
        migrations.AlterField(
            model_name='users',
            name='max_activity_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Activity Streak'),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_activities',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Activities'),
        ),
        migrations.AlterField(
            model_name='users',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Total XP'),
        ),
    ]
