# Generated by Django 5.2.4 on 2025-11-29 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_articles_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), blank=True, default=list, null=True, size=None),
        ),
    ]
