# Generated by Django 6.0.3 on 2026-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_users_level_alter_activity_elapsed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('developer', 'developer'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
