# Generated by Django 5.2.4 on 2025-11-29 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_articles_category_articles_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), default=list, size=None),
        ),
    ]
