# Generated by Django 6.0.3 on 2026-06-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('data', models.CharField(max_length=50, verbose_name='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='app.users', verbose_name='User')),
            ],
        ),
    ]
