# Generated by Django 6.0.3 on 2026-06-02 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_specialbadges'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialbadges',
            name='obtained_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Obtained In'),
            preserve_default=False,
        ),
    ]
