# Generated by Django 5.2.4 on 2025-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_articles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blog_subscribe',
            field=models.BooleanField(default=False, verbose_name='app Subscribe'),
        ),
    ]
