# Generated by Django 6.0.3 on 2026-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_specialbadges_obtained_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='image_filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Filename'),
        ),
    ]
