# Generated by Django 6.0.3 on 2026-06-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_exercises_image_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBioLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('url', models.CharField(max_length=200, verbose_name='URL Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.users', verbose_name='User')),
            ],
        ),
    ]
