# Generated by Django 5.2.4 on 2025-12-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_users_blog_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='visitors',
            field=models.IntegerField(default=0, verbose_name='Visitors'),
        ),
        migrations.CreateModel(
            name='ArticleForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='app.articles', verbose_name='Article ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='app.users', verbose_name='User ID')),
            ],
        ),
    ]
