# Generated by Django 5.2.4 on 2025-12-09 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_articles_visitors_articleforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleforum',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleforum',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.articleforum'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.articles', verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.users', verbose_name='User ID'),
        ),
    ]
