# Generated by Django 6.0.3 on 2026-06-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userbiolinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBioLinks',
            new_name='bioLinks',
        ),
    ]
