# Generated by Django 6.0.3 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_userbiolinks_biolinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biolinks',
            name='url',
            field=models.URLField(verbose_name='URL Address'),
        ),
    ]
