# Generated by Django 6.0.3 on 2026-06-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_biolinks_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biolinks',
            name='title',
        ),
    ]
