# Generated by Django 5.2.4 on 2025-12-11 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_reply_articleforum_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleforum',
            name='likes_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Likes From Users'), default=list, size=None),
        ),
    ]
