# Generated by Django 6.0.3 on 2026-06-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_biolinks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='blog_subscribe',
        ),
        migrations.AddField(
            model_name='users',
            name='private_account',
            field=models.BooleanField(default=False, verbose_name='Private Account'),
        ),
        migrations.AlterField(
            model_name='biolinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_links', to='app.users', verbose_name='User'),
        ),
    ]
