# Generated by Django 6.0.3 on 2026-06-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_users_blog_subscribe_users_private_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleforum',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='articleforum',
            name='likes_from_users',
        ),
        migrations.RemoveField(
            model_name='articleforum',
            name='reports_from_users',
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='app.users', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='ArticleForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', max_length=50, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('articleforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articleforum', verbose_name='Article Forum Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('articleforum', 'user')},
            },
        ),
        migrations.AddField(
            model_name='articleforum',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='liked_article_forum_comments', to='app.users', verbose_name='Likes From Users'),
        ),
        migrations.AddField(
            model_name='articleforum',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, related_name='reported_article_forum_comments', through='app.ArticleForumReport', to='app.users', verbose_name='Reports From Users'),
        ),
    ]
