# Generated by Django 6.0.3 on 2026-06-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_articleforum_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='rating',
        ),
        migrations.CreateModel(
            name='ArticleForumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articles', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='rating_from_users',
            field=models.ManyToManyField(blank=True, through='app.ArticleForumRating', to='app.users', verbose_name='Rating From Users'),
        ),
    ]
