# Generated by Django 6.0.3 on 2026-06-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_articles_rating_articleforumrating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleForumRating',
            new_name='ArticleRating',
        ),
    ]
