# Generated by Django 6.0.3 on 2026-06-14 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_articleforumrating_articlerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='html_filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='HTML Filename'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Image File'),
            preserve_default=False,
        ),
    ]
