# Generated by Django 5.2.4 on 2025-12-27 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_activity_formatted_elapsed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50, verbose_name='Exercise')),
                ('sets', models.IntegerField(default=1, verbose_name='Sets')),
                ('reps', models.IntegerField(default=1, verbose_name='Reps')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_plans', to='app.users', verbose_name='User ID')),
            ],
        ),
    ]
