# Generated by Django 6.0.3 on 2026-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_articles_content_articles_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='html_filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HTML Filename'),
        ),
    ]
