# Generated by Django 5.2.4 on 2025-12-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_trainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='type',
            field=models.CharField(default='Pull', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='reps',
            field=models.IntegerField(default=0, verbose_name='Reps'),
        ),
    ]
