# Generated by Django 6.0.3 on 2026-06-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_articles_html_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', max_length=50, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='app.users', verbose_name='Reported User')),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='app.users', verbose_name='Reporting User')),
            ],
            options={
                'unique_together': {('reported_user', 'reporting_user')},
            },
        ),
    ]
