# Generated by Django 6.0.3 on 2026-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_usersreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reports',
            field=models.PositiveIntegerField(default=0, verbose_name='Reports'),
        ),
    ]
