# Generated by Django 6.0.3 on 2026-06-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_users_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='Is Muted Video'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Comment'),
        ),
    ]
