# Generated by Django 5.2.4 on 2026-01-04 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_trainingplan_day_alter_trainingplan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='sets',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Reps'), default=[0], size=None),
        ),
    ]
