# Generated by Django 6.0.3 on 2026-06-20 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_postmedia_is_muted_alter_articleforum_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Difficulty Percentage'),
        ),
        migrations.AddField(
            model_name='articles',
            name='rarity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rarity Percentage'),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Strength Percentage'),
        ),
        migrations.AddField(
            model_name='articles',
            name='technique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Technique Percentage'),
        ),
        migrations.AddField(
            model_name='articles',
            name='time_to_learn',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Time To Learn Percentage'),
        ),
        migrations.AddField(
            model_name='articles',
            name='time_to_learn_text',
            field=models.CharField(default='TEST', max_length=20, verbose_name='Time To Learn Text'),
            preserve_default=False,
        ),
    ]
