# Generated by Django 5.2.4 on 2026-01-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_trainingplan_reps_remove_trainingplan_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], null=True, verbose_name='Day'),
        ),
    ]
