# Generated by Django 5.2.4 on 2026-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_trainingplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
