# Generated by Django 6.0.3 on 2026-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_articles_difficulty_articles_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rejection_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejection Time'),
        ),
    ]
