# Generated by Django 6.0.3 on 2026-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_reviews_rejection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='suspension_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspension Time'),
        ),
    ]
