# Generated by Django 5.2.4 on 2026-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_trainingplan_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='Day'),
        ),
    ]
