# Generated by Django 6.0.3 on 2026-06-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_users_suspension_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='data_saving_mode',
            field=models.BooleanField(default=False, verbose_name='Data Saving Mode'),
        ),
    ]
