# Generated by Django 5.2.4 on 2026-01-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_activity_type_alter_trainingplan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.IntegerField(null=True, verbose_name='Day'),
        ),
    ]
