# Generated by Django 6.0.3 on 2026-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_users_following_followrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_set', through='app.FollowRelation', to='app.users', verbose_name='Following'),
        ),
    ]
