# Generated by Django 5.2.4 on 2026-01-07 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_activity_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50, verbose_name='Exercise')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), default=list, size=None)),
            ],
        ),
    ]
