# Generated by Django 6.0.3 on 2026-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_users_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='app.FollowRelation', to='app.users', verbose_name='Following'),
        ),
    ]
