# Generated by Django 6.0.3 on 2026-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_users_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='total_watch_time',
            field=models.FloatField(blank=True, help_text='Total Video Watch Time In Seconds.', null=True, verbose_name='Total Watch Time'),
        ),
    ]
