# Generated by Django 6.0.3 on 2026-07-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_postmedia_total_watch_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='app.postmedia', verbose_name='Post Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('post_media', 'user')},
            },
        ),
    ]
