# Generated by Django 5.2.4 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_exercises_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds')], default='reps', verbose_name='Unit'),
        ),
    ]
