# Generated by Django 6.0.3 on 2026-07-06 16:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='sprite_sheet',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.getPostUploadPath, verbose_name='Sprite Sheet'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='vtt_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.getPostUploadPath, verbose_name='VTT File Map'),
        ),
        migrations.AlterField(
            model_name='users',
            name='daily_official_tasks',
            field=models.ManyToManyField(blank=True, help_text="User's Random Generated Daily Official Tasks.", through='app.UserDailyOfficialTasks', to='app.officialtasks', verbose_name='Daily Official Tasks'),
        ),
    ]
