# Generated by Django 6.0.3 on 2026-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is Edited'),
        ),
    ]
