# Generated by Django 5.2.4 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_exercises_requires_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='training_plan_key',
            field=models.CharField(default='None', max_length=50, verbose_name='Training Plan Key'),
        ),
    ]
