# Generated by Django 6.0.3 on 2026-07-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_chat_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='app.chat', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='reacted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='reacted_messages', through='app.MessageReaction', to='app.users', verbose_name='Reactions'),
        ),
    ]
