# Generated by Django 6.0.3 on 2026-07-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_messagereaction_chat_reacted_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=set(),
        ),
    ]
