# Generated by Django 6.0.3 on 2026-07-12 11:55

import app.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_messagereaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the activity in seconds.', verbose_name='Elapsed Time (Seconds)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Activity end time.', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gained_xp',
            field=models.PositiveIntegerField(default=0, help_text='Amount of XP received for activity.', verbose_name='Gained XP'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='training_plan_day',
            field=models.PositiveIntegerField(blank=True, help_text='Assigned activity day.', null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='training_plan_summary',
            field=models.JSONField(blank=True, default=list, help_text='Data recorded for an activity completed according to the training plan.', null=True, verbose_name='Training Plan Summary'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(help_text='Selected activity name.', max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(help_text='The user to whom the activity record belongs.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='article',
            field=models.ForeignKey(help_text='Time the article rating was submitted.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.articles', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='comment',
            field=models.TextField(help_text='Comment content.', max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the comment was written.', verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Comment nesting level (1 is a main comment; deeper levels are replies)', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes on the comment.', verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who liked the comment.', related_name='liked_article_forum_comments', to='app.users', verbose_name='Likes From Users'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Link to the parent comment in the case of a reply.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.articleforum', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='reports',
            field=models.PositiveIntegerField(default=0, help_text='Amount of received reports of the comment.', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who reported the comment.', related_name='reported_article_forum_comments', through='app.ArticleForumReport', to='app.users', verbose_name='Reports From Users'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', help_text='Current status of the comment.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote the comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articleforumreport',
            name='articleforum',
            field=models.ForeignKey(help_text='The article comment that received a report.', on_delete=django.db.models.deletion.CASCADE, to='app.articleforum', verbose_name='Article Forum Comment'),
        ),
        migrations.AlterField(
            model_name='articleforumreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Report submission time.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='articleforumreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='articleforumreport',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the report.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='article',
            field=models.ForeignKey(help_text='The article to which the given rating applies.', on_delete=django.db.models.deletion.CASCADE, to='app.articles', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the article rating was submitted.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating from 1 to 5.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='user',
            field=models.ForeignKey(help_text='The user who rated the article.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Categories corresponding to the article.', max_length=50, verbose_name='Categories'), default=list),
        ),
        migrations.AlterField(
            model_name='articles',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of the article creation.', verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(help_text='Description of the article.', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='difficulty',
            field=models.IntegerField(default=0, help_text='Exercise difficulty in percent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Difficulty Percentage'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='html_filename',
            field=models.CharField(blank=True, help_text='Filename of the HTML template of the article.', max_length=50, null=True, verbose_name='HTML Filename'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_name',
            field=models.CharField(help_text='Filename of the banner image of the article.', max_length=50, verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(help_text='URL of the article.', max_length=50, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='rarity',
            field=models.IntegerField(default=0, help_text='Exercise rarity in percent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rarity Percentage'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='rating_from_users',
            field=models.ManyToManyField(blank=True, help_text='User rating of the article.', through='app.ArticleRating', to='app.users', verbose_name='Rating From Users'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength',
            field=models.IntegerField(default=0, help_text='Exercise required strength in percent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Strength Percentage'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='technique',
            field=models.IntegerField(default=0, help_text='The technical difficulty value of the exercise, expressed as a percentage.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Technique Percentage'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time_to_learn',
            field=models.IntegerField(default=0, help_text='Exercise time to learn in percent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Time To Learn Percentage'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time_to_learn_text',
            field=models.CharField(help_text='Exercise time to learn labeled text.', max_length=20, verbose_name='Time To Learn Text'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(help_text='Title of the article.', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(help_text='The user who owns the article.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='visitors',
            field=models.PositiveIntegerField(default=0, help_text="Amount of the article's visitors.", verbose_name='Visitors'),
        ),
        migrations.AlterField(
            model_name='biolinks',
            name='url',
            field=models.URLField(help_text='URL of the added link.', verbose_name='URL Address'),
        ),
        migrations.AlterField(
            model_name='biolinks',
            name='user',
            field=models.ForeignKey(help_text='The user who added the link to their bio.', on_delete=django.db.models.deletion.CASCADE, related_name='bio_links', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(help_text='Message content.', max_length=250, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Message sending time.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Stores the information if the message was edited.', verbose_name='Is Edited'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Stores the information if the message is read.', verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='reacted_users',
            field=models.ManyToManyField(blank=True, help_text='Users who reacted to the message.', null=True, related_name='reacted_messages', through='app.MessageReaction', to='app.users', verbose_name='Reactions'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Message receiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='app.users', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message sender.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='app.users', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of creation of the task.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Stores the information if the task is completed.', verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the task.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='title',
            field=models.CharField(help_text='Title of the custom task.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='customtasks',
            name='user',
            field=models.ForeignKey(help_text='The user who created a custom task.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Categories'), default=list, help_text='Categories the given exercise falls into.'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='exercise',
            field=models.CharField(help_text='Exercise name.', max_length=50, verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Stores the filename of the exercise image.', max_length=50, null=True, verbose_name='Image Filename'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='requires_weight',
            field=models.BooleanField(default=False, help_text='Stores the information if the exercise requires the additional weight.', verbose_name='Requires Weight'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', help_text='The unit in which the exercise is measured.', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of the follow relation creation.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='from_user',
            field=models.ForeignKey(help_text='Follow from the selected user.', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='app.users'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='accepted', help_text='Status of the follow relation.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='to_user',
            field=models.ForeignKey(help_text='Follow to the selected user.', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='app.users'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='chat',
            field=models.ForeignKey(help_text='The message to which the reaction belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='app.chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the reaction was added.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='emoji',
            field=models.CharField(help_text='Emoji added as a reaction.', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(help_text='The user who added a reaction to the message.', on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='officialtasks',
            name='data',
            field=models.CharField(help_text='Spaceless title of the task used in the programming logic.', max_length=100, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='officialtasks',
            name='title',
            field=models.CharField(help_text='Title of the task.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='officialtasks',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Amount of XP upon completing the task.', verbose_name='XP'),
        ),
        migrations.AlterField(
            model_name='post',
            name='added_hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Added Hashtags'), default=list, help_text='Hashtags added to the post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Stores the information if the comments are allowed for the post.', verbose_name='Allow Comments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The exact coordinates of the location added to the post in WGS84 (Standardized, Geocentric Coordinate System Used Globally For Mapping, Navigation And GPS) format.', null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of creation of the post.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the post.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hide_likes',
            field=models.BooleanField(default=False, help_text="Stores the information if the post's likes are hidden.", verbose_name='Hide Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='latest_interaction',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time of the last recorded interaction with the post (new comment, like).', verbose_name='Latest Interaction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Total amount of obtained likes.', verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who liked the post.', related_name='liked_posts', to='app.users', verbose_name='Likes From Users'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Location added to the post.', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_visibility',
            field=models.BooleanField(default=True, help_text='Stores the information if the post is visible for public.', verbose_name='Public Visibility'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reports',
            field=models.PositiveIntegerField(default=0, help_text='Amount of received reports of the post.', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who reported the post.', related_name='reported_posts', through='app.PostReport', to='app.users', verbose_name='Reports From Users'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seen_by',
            field=models.ManyToManyField(help_text='Users who have already seen the post.', related_name='viewed_posts', through='app.SeenPost', to='app.users', verbose_name='Seen By'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, help_text='Users tagged in the post.', to='app.users', verbose_name='Tagged Users'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(help_text='The user who uploaded the post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='comment',
            field=models.TextField(help_text='Comment content.', max_length=100, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the comment was added.', verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Comment nesting level (1 is a main comment; deeper levels are replies)', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Amount of obtained likes on the comment.', verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who liked the comment.', related_name='liked_post_forum_comments', to='app.users', verbose_name='Likes From Users'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Link to the parent comment in the case of a reply.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.postforum', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='post',
            field=models.ForeignKey(help_text='The post to which the comment belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='reports',
            field=models.PositiveIntegerField(default=0, help_text='Amount of received reports of the comment.', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who reported the comment.', related_name='reported_post_forum_comments', through='app.PostForumReport', to='app.users', verbose_name='Reports From Users'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', help_text='Current status of the comment.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='user',
            field=models.ForeignKey(help_text='The user who added the comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='postforumreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Report submission time.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='postforumreport',
            name='postforum',
            field=models.ForeignKey(help_text='The post comment that received a report.', on_delete=django.db.models.deletion.CASCADE, to='app.postforum', verbose_name='Post Forum Comment'),
        ),
        migrations.AlterField(
            model_name='postforumreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='postforumreport',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the report.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='compressed_size',
            field=models.BigIntegerField(blank=True, help_text='Compressed size of the uploaded file.', null=True, verbose_name='Compressed Size'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(help_text='Path to the file.', upload_to=app.models.getPostUploadPath, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='Stores the information if the uploaded video is muted.', verbose_name='Is Muted Video'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Stores the information if the uploaded file is already processed.', verbose_name='Is Processed'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Stores the information if the uploaded file is a video.', verbose_name='Is Video'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the uploaded file in post.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded file.', max_length=255, null=True, verbose_name='Original Filename'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='original_size',
            field=models.BigIntegerField(blank=True, help_text='Original size of the uploaded file.', null=True, verbose_name='Original Size'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(help_text='The post to which the given medium belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='sprite_sheet',
            field=models.ImageField(blank=True, help_text='Video image sprite sheet for scrubbar preview.', null=True, upload_to=app.models.getPostUploadPath, verbose_name='Sprite Sheet'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Path to the video thumbnail.', null=True, upload_to=app.models.getPostUploadPath, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='total_watch_time',
            field=models.FloatField(blank=True, help_text='Total video watch time in seconds.', null=True, verbose_name='Total Watch Time'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='vtt_file',
            field=models.FileField(blank=True, help_text='VTT file map of the video sprite sheet.', null=True, upload_to=app.models.getPostUploadPath, verbose_name='VTT File Map'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Report submission time.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(help_text='The post that received a report.', on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the report.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of review report submission.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', help_text='Reason for reporting the review.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(help_text='A review that has been reported.', on_delete=django.db.models.deletion.CASCADE, to='app.reviews', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='user',
            field=models.ForeignKey(help_text='The user who reported the review.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of the review submission.', verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='last_edit',
            field=models.DateTimeField(blank=True, help_text='Time of the last editing.', null=True, verbose_name='Last Edit Time'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating from 1 to 5.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rejection_time',
            field=models.DateTimeField(blank=True, help_text='Review rejection time.', null=True, verbose_name='Rejection Time'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reports',
            field=models.PositiveIntegerField(default=0, help_text='Amount of total obtained reports.', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, help_text='Users who submitted a report.', related_name='reported_reviews', through='app.ReviewReport', to='app.users', verbose_name='Reports From Users'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(help_text='Content of the written review.', max_length=200, null=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('hidden', 'hidden')], default='pending', help_text='Current status of the written review.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='seenpost',
            name='post',
            field=models.ForeignKey(help_text='A post that has been viewed.', on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_instances', to='app.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='seenpost',
            name='user',
            field=models.ForeignKey(help_text='User who viewed the post.', on_delete=django.db.models.deletion.CASCADE, related_name='seen_instances', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='seenpost',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Post view time.', verbose_name='Viewed At'),
        ),
        migrations.AlterField(
            model_name='specialbadges',
            name='data',
            field=models.CharField(help_text='Spaceless title of the badge used in the programming logic.', max_length=50, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='specialbadges',
            name='obtained_in',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of receivation of the badge.', verbose_name='Obtained In'),
        ),
        migrations.AlterField(
            model_name='specialbadges',
            name='title',
            field=models.CharField(help_text='Full title of the badge.', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialbadges',
            name='user',
            field=models.ForeignKey(help_text='Stores the receiver Of the Badge.', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.PositiveIntegerField(blank=True, help_text='Training plan day.', null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='exercise',
            field=models.CharField(help_text='Exercise name.', max_length=50, verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the exercise in the training plan.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name='Reps'), default=list, help_text='Exercise periods (the length of the array represents sets and the amount of reps represents the values (0 = to failute / max. reps).'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='training_plan_key',
            field=models.CharField(default='None', help_text='Random identification key for the training plan.', max_length=50, verbose_name='Training Plan Key'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='type',
            field=models.CharField(help_text='Training plan name.', max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', help_text='The unit in which the exercise is measured.', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(help_text='The user to whom the training plan belongs.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_plans', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volume of processed funds in EUR.', max_digits=10, verbose_name='Amount (€)'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cardholder_name',
            field=models.CharField(help_text="Cardholder's name.", max_length=50, verbose_name='Cardholder Name'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Transaction addition time.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', help_text='Status of the added transaction.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='stripe_intent_id',
            field=models.CharField(help_text='Transaction ID in the Stripe service.', max_length=255, unique=True, verbose_name='Stripe ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(help_text='The user who created the transaction.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userdailyofficialtasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of the generation of the task.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userdailyofficialtasks',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Stores the information if the task is completed.', verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='userdailyofficialtasks',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Task's progress percentage of completion.", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Progress Percentage'),
        ),
        migrations.AlterField(
            model_name='userdailyofficialtasks',
            name='task',
            field=models.ForeignKey(help_text='Full title of the task.', on_delete=django.db.models.deletion.CASCADE, to='app.officialtasks', verbose_name='Official Task'),
        ),
        migrations.AlterField(
            model_name='userdailyofficialtasks',
            name='user',
            field=models.ForeignKey(help_text='The user to whom the task belongs.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('unverified', 'unverified'), ('OK', 'OK'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='unverified', help_text="User's account Status.", max_length=20, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activity_streak',
            field=models.PositiveIntegerField(default=0, help_text="User's current activity streak.", verbose_name='Activity Streak'),
        ),
        migrations.AlterField(
            model_name='users',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text="User's account creation time.", verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='daily_official_tasks',
            field=models.ManyToManyField(blank=True, help_text="User's random generated daily official tasks.", through='app.UserDailyOfficialTasks', to='app.officialtasks', verbose_name='Daily Official Tasks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='data_saving_mode',
            field=models.BooleanField(default=False, help_text='Stores the information if the user has turned on the data saving mode.', verbose_name='Data Saving Mode'),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, help_text="User's follow relations with other users.", related_name='followers', through='app.FollowRelation', to='app.users', verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='users',
            name='friend_code',
            field=models.CharField(help_text="User's random generated friend code.", max_length=6, verbose_name='Friend Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(default='en', help_text="User's default preferred language.", max_length=10, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_activity_streak_increase_time',
            field=models.DateTimeField(blank=True, help_text="Stores the user's last activity streak increase time.", null=True, verbose_name='Last Activity Streak Increase time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_edit',
            field=models.DateTimeField(blank=True, help_text='Time of the last account edition (only crucial changes).', null=True, verbose_name='Last Edit Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text="Stores the time of the user's last login.", null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='max_activity_streak',
            field=models.PositiveIntegerField(default=0, help_text="Stores the user's maximum activity streak.", verbose_name='Max Activity Streak'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(help_text="User's hashed password.", max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_reset_code',
            field=models.CharField(blank=True, help_text="User's password reset code to change the password.", max_length=6, null=True, verbose_name='Password Reset Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='private_account',
            field=models.BooleanField(default=False, help_text="Stores the information if the user's account is private.", verbose_name='Private Account'),
        ),
        migrations.AlterField(
            model_name='users',
            name='reports',
            field=models.PositiveIntegerField(default=0, help_text="User's reports amount.", verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='users',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, help_text="User's saved posts of other users.", related_name='saved_posts', to='app.post', verbose_name='Saved Posts'),
        ),
        migrations.AlterField(
            model_name='users',
            name='suspension_time',
            field=models.DateTimeField(blank=True, help_text="Stores the user's suspension time if had any.", null=True, verbose_name='Suspension time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, help_text="User's verification code to activate account.", max_length=6, null=True, verbose_name='Verification Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text="User's total amount of obtained XP.", verbose_name='Total XP'),
        ),
        migrations.AlterField(
            model_name='users',
            name='xp_boost_expiration_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Stores the last time of XP boost expiration.', verbose_name='XP Boost Expiration Time'),
        ),
        migrations.AlterField(
            model_name='usersreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the report was submitted.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usersreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'spam'), ('harassment', 'harassment'), ('hate_speech', 'hate speech'), ('misinformation', 'misinformation'), ('explicit_content', 'explicit content'), ('other', 'other')], default='other', help_text='Reason of the given report.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='usersreport',
            name='reported_user',
            field=models.ForeignKey(help_text='The user against whom the report was filed.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='app.users', verbose_name='Reported User'),
        ),
        migrations.AlterField(
            model_name='usersreport',
            name='reporting_user',
            field=models.ForeignKey(help_text='The user who submitted the report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='app.users', verbose_name='Reporting User'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when the user viewed the video.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='post_media',
            field=models.ForeignKey(help_text='The exact video from the post that was marked as seen.', on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='app.postmedia', verbose_name='Post Media'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='user',
            field=models.ForeignKey(help_text='A user who watched the video.', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='User'),
        ),
    ]
