# Generated by Django 6.0.3 on 2026-07-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_activity_elapsed_time_alter_activity_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID of the Stripe subscription.', max_length=255, null=True, unique=True, verbose_name='Stripe Subscription ID')),
                ('plan', models.CharField(choices=[('free', 'Zadarmo'), ('basic', 'Základné'), ('premium', 'Prémiové')], default='free', help_text='Activated subscription plan.', max_length=20, verbose_name='Plan')),
                ('is_active', models.BooleanField(default=False, help_text='Stores the information if the subscription is still active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the subscription was added.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time the subscription was updated.', verbose_name='Created At')),
                ('user', models.OneToOneField(help_text='The user who activated the subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app.users', verbose_name='User')),
            ],
        ),
    ]
