# Generated by Django 6.0.3 on 2026-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='title',
            field=models.CharField(help_text='Title of the payment.', max_length=20, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cardholder_name',
            field=models.CharField(help_text="Cardholder's name.", max_length=50, null=True, verbose_name='Cardholder Name'),
        ),
    ]
