# Generated by Django 5.2.4 on 2026-03-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_activity_day_alter_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='day',
            new_name='training_plan_day',
        ),
    ]
