# Generated by Django 6.0.3 on 2026-03-17 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_day_activity_training_plan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleforum',
            name='likes_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Likes From Users'), default=list),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='reports_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Reports From Users'), default=list),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Reps'), default=list),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('OK', 'OK'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='OK', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Followers'), default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Following'), default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
