# Generated by Django 6.0.3 on 2026-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_transactions_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Stores the information if the subscription is cancelled. The subscription will end at the end of the billing period.', verbose_name='Is Cancelled'),
        ),
    ]
