# Generated by Django 6.0.3 on 2026-07-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_subscription_is_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Training Session', 'verbose_name_plural': 'Aktivity'},
        ),
        migrations.AlterModelOptions(
            name='articleforum',
            options={'verbose_name': 'Komentár článku', 'verbose_name_plural': 'Komentáre článkov'},
        ),
        migrations.AlterModelOptions(
            name='articleforumreport',
            options={'verbose_name': 'Nahlásenie komentáru článku', 'verbose_name_plural': 'Nahlásenia komentárov článkov'},
        ),
        migrations.AlterModelOptions(
            name='articlerating',
            options={'verbose_name': 'Recenzia článku', 'verbose_name_plural': 'Recenzie článkov'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Články'},
        ),
        migrations.AlterModelOptions(
            name='followrelation',
            options={'verbose_name': 'Vzťah užívateľov'},
        ),
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'verbose_name': 'Nahlásená recenzia', 'verbose_name_plural': 'Nahlásené recenzie'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Recenzia', 'verbose_name_plural': 'Recenzie'},
        ),
        migrations.AlterModelOptions(
            name='specialbadges',
            options={'verbose_name': 'Špeciálny odznak', 'verbose_name_plural': 'Špeciálne odznaky'},
        ),
        migrations.AlterModelOptions(
            name='userdailyofficialtasks',
            options={'verbose_name': 'Denná oficiálna úloha užívateľa', 'verbose_name_plural': 'Denné oficiálne úlohy užívateľov'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['creation_time'], 'verbose_name': 'Užívateľ', 'verbose_name_plural': 'Užívatelia'},
        ),
        migrations.AlterModelOptions(
            name='usersreport',
            options={'verbose_name': 'Nahlásenie užívateľa', 'verbose_name_plural': 'Nahlásenia užívateľov'},
        ),
    ]
