# Generated by Django 6.0.3 on 2026-07-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_activity_options_alter_articleforum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biolinks',
            options={'verbose_name': 'Bio odkaz', 'verbose_name_plural': 'Bio odkazy'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Správa', 'verbose_name_plural': 'Správy'},
        ),
        migrations.AlterModelOptions(
            name='customtasks',
            options={'verbose_name': 'Vlastná úloha', 'verbose_name_plural': 'Vlastné úlohy'},
        ),
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name': 'Cvik', 'verbose_name_plural': 'Cviky'},
        ),
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'verbose_name': 'Správa', 'verbose_name_plural': 'Správy'},
        ),
        migrations.AlterModelOptions(
            name='officialtasks',
            options={'verbose_name': 'Oficiálna úloha', 'verbose_name_plural': 'Oficiálne úlohy'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Príspevky'},
        ),
        migrations.AlterModelOptions(
            name='postforum',
            options={'verbose_name': 'Komentár príspevku', 'verbose_name_plural': 'Komentáre príspevkov'},
        ),
        migrations.AlterModelOptions(
            name='postforumreport',
            options={'verbose_name': 'Nahlásenie komentáru príspevku', 'verbose_name_plural': 'Nahlásenia komentárov príspevkov'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'Médium príspevku', 'verbose_name_plural': 'Média príspevkov'},
        ),
        migrations.AlterModelOptions(
            name='postreport',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Príspevky'},
        ),
        migrations.AlterModelOptions(
            name='seenpost',
            options={'verbose_name': 'Označený videný príspevok', 'verbose_name_plural': 'Označenia videných príspevkov'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Predplatné'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'verbose_name': 'Training Plan', 'verbose_name_plural': 'Training Plans'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transakcia', 'verbose_name_plural': 'Transakcie'},
        ),
        migrations.AlterModelOptions(
            name='videoview',
            options={'verbose_name': 'Označené videné video', 'verbose_name_plural': 'Označenia videných videií'},
        ),
    ]
