# Generated by Django 6.0.3 on 2026-07-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_biolinks_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelation',
            name='from_user',
            field=models.ForeignKey(help_text='Follow from the selected user.', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='app.users', verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='accepted', help_text='Status of the follow relation.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='to_user',
            field=models.ForeignKey(help_text='Follow to the selected user.', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='app.users', verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('explicit_content', 'Explicit Content'), ('other', 'other')], default='other', help_text='Reason for reporting the review.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('hidden', 'Hidden')], default='pending', help_text='Current status of the written review.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('OK', 'OK'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='unverified', help_text="User's account Status.", max_length=20, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio.", max_length=100, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.EmailField(help_text="User's e-mail address.", max_length=50, verbose_name='E-mail Address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, help_text="User's first name.", max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='friend_code',
            field=models.CharField(editable=False, help_text="User's random generated friend code.", max_length=6, unique=True, verbose_name='Friend Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, help_text='ID of user registered with Google.', max_length=255, null=True, verbose_name='Google ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name.", max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(help_text="User's phone number.", max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture_name',
            field=models.CharField(blank=True, help_text="User's profile picture filename.", max_length=50, null=True, verbose_name='Profile Picture File'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('admin', 'Admin'), ('user', 'User')], default='user', help_text="User's role.", max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_activities',
            field=models.PositiveIntegerField(default=0, help_text="User's total amount of recorded activities.", verbose_name='Total Activities'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text="User's username.", max_length=20, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='usersreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('explicit_content', 'Explicit Content'), ('other', 'other')], default='other', help_text='Reason of the given report.', max_length=50, verbose_name='Reason'),
        ),
    ]
