# Generated by Django 6.0.3 on 2026-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_users_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Language Code'),
        ),
    ]
