# Generated by Django 6.0.3 on 2026-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_followrelation_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Sender's first name.", max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Sender's last name.", max_length=50, verbose_name='Last Name')),
                ('email_address', models.EmailField(help_text="Sender's e-mail address.", max_length=50, verbose_name='E-mail Address')),
                ('subject', models.CharField(choices=[('question', 'Question'), ('account_issue', 'Account Issue'), ('bug', 'Bug'), ('suggestion', 'Suggestion')], default='question', help_text='Subject of the message.', max_length=20, verbose_name='Subject')),
                ('message', models.TextField(blank=True, help_text='Message content.', max_length=200, null=True, verbose_name='Message')),
                ('attachment', models.CharField(blank=True, help_text='Selected attachment filename.', max_length=250, null=True, verbose_name='Attachment Filename')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Message sending time.', verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('hidden', 'Hidden')], default='OK', help_text='Current status of the comment.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='articleforumreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('explicit_content', 'Explicit Content'), ('other', 'Other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='postforumreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('explicit_content', 'Explicit Content'), ('other', 'Other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('explicit_content', 'Explicit Content'), ('other', 'Other')], default='other', help_text='Reason for reporting.', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='unit',
            field=models.CharField(choices=[('reps', 'Reps'), ('seconds', 'Seconds'), ('steps', 'Steps')], default='reps', help_text='The unit in which the exercise is measured.', max_length=20, verbose_name='Unit'),
        ),
    ]
