# Generated by Django 6.0.3 on 2026-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_users_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('unverified', 'unverified'), ('OK', 'OK'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='unverified', max_length=20, verbose_name='Account Status'),
        ),
    ]
