# Generated by Django 6.0.3 on 2026-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_contactmessage_alter_articleforum_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Training Session', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='articleforum',
            options={'verbose_name': 'Article forum comment', 'verbose_name_plural': 'Article forum comments'},
        ),
        migrations.AlterModelOptions(
            name='articleforumreport',
            options={'verbose_name': 'Article comment report', 'verbose_name_plural': 'Article comment reports'},
        ),
        migrations.AlterModelOptions(
            name='articlerating',
            options={'verbose_name': 'Article review', 'verbose_name_plural': 'Article reviews'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='biolinks',
            options={'verbose_name': 'Bio link', 'verbose_name_plural': 'Bio links'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='customtasks',
            options={'verbose_name': 'Custom task', 'verbose_name_plural': 'Custom tasks'},
        ),
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='followrelation',
            options={'verbose_name': 'Follow relations'},
        ),
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='officialtasks',
            options={'verbose_name': 'Official task', 'verbose_name_plural': 'Official tasks'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postforum',
            options={'verbose_name': 'Post forum comment', 'verbose_name_plural': 'Post forum comments'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'Post media', 'verbose_name_plural': 'Posts media'},
        ),
        migrations.AlterModelOptions(
            name='postreport',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'verbose_name': 'Reported review', 'verbose_name_plural': 'Reported reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='seenpost',
            options={'verbose_name': 'Seen post', 'verbose_name_plural': 'Viewed posts'},
        ),
        migrations.AlterModelOptions(
            name='specialbadges',
            options={'verbose_name': 'Special badge', 'verbose_name_plural': 'Special badges'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userdailyofficialtasks',
            options={'verbose_name': "User's daily official task", 'verbose_name_plural': 'Official daily user tasks'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['creation_time'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersreport',
            options={'verbose_name': 'User report', 'verbose_name_plural': 'User reports'},
        ),
        migrations.AlterModelOptions(
            name='videoview',
            options={'verbose_name': 'Seen video', 'verbose_name_plural': 'Seen videos'},
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Is Staff'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', help_text='Activated subscription plan.', max_length=20, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text="User's username.", max_length=20, unique=True, verbose_name='Username'),
        ),
    ]
