# Generated by Django 6.0.3 on 2026-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_activity_options_alter_articleforum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='is_warm_up',
            field=models.BooleanField(default=False, help_text='Stores the information if the exercise is warm up.', verbose_name='Is Warm Up'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_registered_with_app',
            field=models.BooleanField(default=False, help_text='Stores the information if the user is registered with mobile APP.', verbose_name='Is Registered With APP'),
        ),
    ]
