# Generated by Django 6.0.3 on 2026-09-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_trainingplan_is_warm_up_users_is_registered_with_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='is_custom_exercise',
            field=models.BooleanField(default=False, help_text='Stores the information if the exercise is custom.', verbose_name='Is Custom Exercise'),
        ),
    ]
