# Generated by Django 6.0.3 on 2026-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_rename_payment_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe ID')),
                ('cardholder_name', models.CharField(max_length=50, verbose_name='Cardholder Name')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount (€)')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
