# Generated by Django 6.0.3 on 2026-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='stripe_intent_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
