# Generated by Django 6.0.3 on 2026-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_transactions_stripe_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='stripe_intent_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Stripe ID'),
        ),
    ]
