# Generated by Django 6.0.3 on 2026-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_transactions_stripe_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='blog_subscribe',
            field=models.BooleanField(default=False, verbose_name='Blog Subscribe'),
        ),
    ]
