# Generated by Django 6.0.3 on 2026-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_users_blog_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friend_code',
            field=models.CharField(default='000000', max_length=6, verbose_name='Friend Code'),
        ),
    ]
