# Generated by Django 6.0.3 on 2026-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_users_friend_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friend_code',
            field=models.CharField(max_length=6, verbose_name='Friend Code'),
        ),
    ]
