# Generated by Django 6.0.3 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_users_friend_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='training_plan_summary',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Training Plan Summary'),
        ),
    ]
