# Generated by Django 6.0.3 on 2026-04-09 08:51

import app.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_activity_training_plan_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='@', max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='likes_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Likes From Users'), default=list),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='reports_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Reports From Users'), default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Followers'), default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Following'), default=list),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50, verbose_name='Post Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('tagged_people', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Tagged People'), blank=True, default=list, null=True)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Hashtags'), blank=True, default=list, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Locality')),
                ('public_visibility', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow Comments')),
                ('hide_likes', models.BooleanField(default=False, verbose_name='Hide Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.users', verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.getPostUploadPath)),
                ('is_video', models.BooleanField(default=False, verbose_name='Is Video')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.post', verbose_name='Post')),
            ],
        ),
    ]
