# Generated by Django 6.0.3 on 2026-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_users_username_alter_articleforum_likes_from_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='@', max_length=20, verbose_name='Username'),
        ),
    ]
