# Generated by Django 6.0.3 on 2026-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_post_post_name_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='locality',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
    ]
