# Generated by Django 6.0.3 on 2026-04-16 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_users_first_name_alter_users_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_people',
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Tagged Users'), default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Hashtags'), default=list),
        ),
    ]
