# Generated by Django 6.0.3 on 2026-04-18 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_remove_post_tagged_people_post_tagged_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='added_hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Added Hashtags'), default=list),
        ),
    ]
