# Generated by Django 6.0.3 on 2026-04-19 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_remove_post_hashtags_post_added_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Likes From Users'), default=list),
        ),
    ]
