# Generated by Django 6.0.3 on 2026-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_post_likes_post_likes_from_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, to='app.users', verbose_name='Tagged Users'),
        ),
    ]
