# Generated by Django 6.0.3 on 2026-04-21 16:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_remove_post_tagged_users_post_tagged_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('likes_from_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Likes From Users'), default=list)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', max_length=20, verbose_name='Status')),
                ('reports', models.IntegerField(default=0, verbose_name='Reports')),
                ('reports_from_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Reports From Users'), default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.postforum')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post', verbose_name='Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app.users', verbose_name='User ID')),
            ],
        ),
    ]
