# Generated by Django 6.0.3 on 2026-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_postforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
    ]
