# Generated by Django 6.0.3 on 2026-05-05 04:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_postmedia_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.getPostUploadPath),
        ),
    ]
