# Generated by Django 6.0.3 on 2026-05-07 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_postmedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='saved_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Saved Posts'), default=list),
        ),
    ]
