# Generated by Django 6.0.3 on 2026-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_users_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Bio'),
        ),
    ]
