# Generated by Django 6.0.3 on 2026-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_users_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
