# Generated by Django 6.0.3 on 2026-05-12 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_postforum_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_interaction',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Latest Interaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.articles', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articleforum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_plans', to='app.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='app.users', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='SeenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_instances', to='app.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_instances', to='app.users', verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='seen_by',
            field=models.ManyToManyField(related_name='viewed_posts', through='app.SeenPost', to='app.users'),
        ),
    ]
