# Generated by Django 6.0.3 on 2026-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_post_latest_interaction_alter_activity_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_from_users',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='app.users', verbose_name='Likes From Users'),
        ),
    ]
