# Generated by Django 6.0.3 on 2026-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_remove_post_likes_from_users_post_likes_from_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='likes_from_users',
        ),
        migrations.AddField(
            model_name='postforum',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='liked_post_forum_comments', to='app.users', verbose_name='Likes From Users'),
        ),
    ]
