# Generated by Django 6.0.3 on 2026-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_remove_postforum_likes_from_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='reports_from_users',
        ),
        migrations.AddField(
            model_name='postforum',
            name='reports_from_users',
            field=models.ManyToManyField(blank=True, related_name='reported_post_forum_comments', to='app.users', verbose_name='Reports From Users'),
        ),
    ]
