# Generated by Django 6.0.3 on 2026-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_remove_postforum_reports_from_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='following',
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='app.users', verbose_name='Following'),
        ),
    ]
