# Generated by Django 6.0.3 on 2026-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_remove_users_followers_remove_users_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='saved_posts',
        ),
        migrations.AddField(
            model_name='users',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='app.post', verbose_name='Saved Posts'),
        ),
    ]
