# Generated by Django 6.0.3 on 2026-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_remove_users_saved_posts_users_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='compressed_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Compressed Size'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='original_size',
            field=models.BigIntegerField(default=0, verbose_name='Original Size'),
            preserve_default=False,
        ),
    ]
