# Generated by Django 6.0.3 on 2026-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_postmedia_compressed_size_postmedia_original_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='original_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Original Size'),
        ),
    ]
