# Generated by Django 6.0.3 on 2026-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_postmedia_original_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Filename'),
        ),
    ]
