version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: swzilina_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7.0.11-alpine
    container_name: swzilina_redis

  # Django
  web:
    build: ./swzilina
    container_name: swzilina_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./swzilina:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Celery
  celery:
    build: ./swzilina
    container_name: swzilina_celery
    command: celery -A swzilina worker -l INFO
    volumes:
      - ./swzilina:/app
      - ./swzilina/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  # Celery Beat
  celery_beat:
    build: ./swzilina
    container_name: swzilina_beat
    command: celery -A swzilina beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./swzilina:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  # Flower
  flower:
    build: ./swzilina
    container_name: swzilina_flower
    command: celery -A swzilina flower --port=5555
    volumes:
      - ./swzilina:/app
    ports:
      - "5557:5555"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data: