version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: wesiq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7.0.11-alpine
    container_name: wesiq_redis

  # Django
  web:
    build: ./wesiq
    container_name: wesiq_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wesiq:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Celery
  celery:
    build: ./wesiq
    container_name: wesiq_celery
    command: celery -A core worker -l INFO
    volumes:
      - ./wesiq:/app
      - ./wesiq/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  # Celery Beat
  celery_beat:
    build: ./wesiq
    container_name: wesiq_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./wesiq:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  # Flower
  flower:
    build: ./wesiq
    container_name: wesiq_flower
    command: celery -A core flower --port=5555
    volumes:
      - ./wesiq:/app
    ports:
      - "5557:5555"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data: