# Generated by Django 5.2.4 on 2025-10-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email_address', models.CharField(max_length=50, verbose_name='E-mail Address')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', verbose_name='Role')),
            ],
        ),
    ]
