# Generated by Django 5.2.4 on 2025-10-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SWZilinaUsers',
        ),
    ]
