# Generated by Django 5.2.4 on 2025-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_users_profile_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='profile_picture'),
        ),
    ]
