# Generated by Django 5.2.4 on 2025-10-30 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
