# Generated by Django 5.2.4 on 2025-11-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_articles_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.CharField(default='URL', max_length=50, verbose_name='URL / Class'),
        ),
    ]
