# Generated by Django 5.2.4 on 2025-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_articles_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image File'),
        ),
    ]
