# Generated by Django 5.2.4 on 2025-11-28 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_articles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Time'),
            preserve_default=False,
        ),
    ]
