# Generated by Django 5.2.4 on 2025-12-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_articleforum_creation_time_articleforum_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleforum',
            old_name='reply',
            new_name='parent',
        ),
    ]
