# Generated by Django 5.2.4 on 2025-12-12 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_articleforum_likes_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleforum',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AddField(
            model_name='articleforum',
            name='reports_from_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Reports From Users'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='articleforum',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('hidden', 'hidden')], default='OK', verbose_name='Status'),
        ),
    ]
