# Generated by Django 5.2.4 on 2025-12-20 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_articleforum_reports_articleforum_reports_from_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Followers'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Following'), default=list, size=None),
        ),
    ]
