# Generated by Django 5.2.4 on 2025-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_users_followers_users_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Total XP'),
        ),
    ]
