# Generated by Django 5.2.4 on 2025-12-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_users_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='End Time')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='Elapsed Time (Seconds)')),
                ('gained_xp', models.IntegerField(default=0, verbose_name='Gained XP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='blog.users', verbose_name='User ID')),
            ],
        ),
    ]
