# Generated by Django 5.2.4 on 2025-12-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='formatted_elapsed_time',
            field=models.CharField(default='00h 00m 01s', max_length=11, verbose_name='Formatted Elapsed Time'),
        ),
    ]
