# Generated by Django 5.2.4 on 2025-12-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_trainingplan_day_trainingplan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
    ]
