# Generated by Django 5.2.4 on 2026-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_trainingplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type'),
        ),
    ]
