# Generated by Django 5.2.4 on 2026-01-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_activity_day_alter_trainingplan_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
    ]
