# Generated by Django 5.2.4 on 2026-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day'),
        ),
    ]
