# Generated by Django 5.2.4 on 2026-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_trainingplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds')], default='reps', verbose_name='Unit'),
        ),
    ]
