# Generated by Django 5.2.4 on 2026-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_trainingplan_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='requires_weight',
            field=models.BooleanField(default=False, verbose_name='Requires Weight'),
        ),
    ]
