# Generated by Django 5.2.4 on 2026-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_trainingplan_training_plan_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='unit',
            field=models.CharField(choices=[('reps', 'reps'), ('seconds', 'seconds'), ('steps', 'steps')], default='reps', verbose_name='Unit'),
        ),
    ]
