# Generated by Django 5.2.4 on 2026-02-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_exercises_unit_alter_trainingplan_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('OK', 'OK'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='OK', verbose_name='Account Status'),
        ),
    ]
