# Generated by Django 5.2.4 on 2026-03-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Login'),
        ),
    ]
