# Generated by Django 6.0.3 on 2026-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_alter_articleforum_likes_from_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Language Code'),
        ),
    ]
