# Generated by Django 6.0.3 on 2026-03-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
    ]
