--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-01-25 18:17:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 263 (class 1259 OID 17116)
-- Name: blog_exercises; Type: TABLE; Schema: public; Owner: swzilina_admin
--

CREATE TABLE public.blog_exercises (
    id bigint NOT NULL,
    exercise character varying(50) NOT NULL,
    categories character varying(50)[] NOT NULL,
    unit character varying NOT NULL,
    requires_weight boolean NOT NULL
);


ALTER TABLE public.blog_exercises OWNER TO swzilina_admin;

--
-- TOC entry 262 (class 1259 OID 17115)
-- Name: blog_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: swzilina_admin
--

ALTER TABLE public.blog_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4933 (class 0 OID 17116)
-- Dependencies: 263
-- Data for Name: blog_exercises; Type: TABLE DATA; Schema: public; Owner: swzilina_admin
--

COPY public.blog_exercises (id, exercise, categories, unit, requires_weight) FROM stdin;
2	Push Up	{Push}	reps	f
1	Dip	{Push}	reps	f
0	Pull Up	{Pull}	reps	f
5	Pistol Squat	{Legs}	reps	f
9	Bar Dip	{}	reps	f
8	One Arm Push Up	{}	reps	f
7	One Arm Pull Up	{}	reps	f
12	Knee Push Up	{}	reps	f
11	Australian Pull Up	{}	reps	f
10	Korean Dip	{}	reps	f
13	Handstand Push Up	{}	reps	f
18	Scapular Pull Up	{}	reps	f
17	Lower Back Extension	{}	reps	f
14	Clap Push Up	{}	reps	f
21	Front Lever Press	{}	reps	f
20	Front Lever Pull Up	{}	reps	f
19	Chin Up	{}	reps	f
25	Pullover	{}	reps	f
29	Archer Push Up	{}	reps	f
28	Pike Push Up	{}	reps	f
26	Toes To Bar	{}	reps	f
30	Bulgarian Push Up	{}	reps	f
6	Handstand	{Balance,Push}	seconds	f
4	Front Lever	{Static,Pull}	seconds	f
22	Back Lever	{}	seconds	f
24	V-Sit	{}	seconds	f
23	L-Sit	{}	seconds	f
27	Hang On Bar	{}	seconds	f
31	90 Degree Handstand Push Up	{}	reps	f
3	Squat	{Legs}	reps	f
16	Bench Press	{}	reps	t
15	Deadlift	{}	reps	t
33	Incline Push Up	{}	reps	f
32	Decline Push Up	{}	reps	f
42	Planche Lean	{}	seconds	f
41	Advanced Tuck Front Lever	{}	seconds	f
40	Tuck Front Lever	{}	seconds	f
39	Straddle Front Lever	{}	seconds	f
38	Straddle Planche	{}	seconds	f
37	Tuck Planche	{}	seconds	f
36	Planche Push Up	{}	reps	f
35	Planche Press	{}	reps	f
34	Planche	{}	seconds	f
43	Advanced Tuck Planche	{}	seconds	f
47	Front Squat	{}	reps	t
46	Human Flag	{}	seconds	f
45	Dragon Flag	{}	seconds	f
44	Biceps Curl	{}	reps	t
50	Sissy Squat	{}	reps	f
49	Jump Squat	{}	reps	f
48	Bulgarian Split Squat	{}	reps	f
56	Dumbbell Pullover	{}	reps	t
55	Incline Dumbbell Bench Press	{}	reps	t
54	Bent Over Dumbbell Row	{}	reps	t
53	One Arm Dumbbell Row	{}	reps	t
52	Dumbbell Bench Press	{}	reps	t
51	Dumbbell Lateral Raise	{}	reps	t
65	Crunch	{}	reps	f
64	Sit Up	{}	reps	f
62	Dumbbell Flys	{}	reps	t
61	Tricep Extension	{}	reps	t
60	Military Press	{}	reps	t
59	Bent Over Dumbbell Reverse Fly	{}	reps	t
58	Bent Over Row	{}	reps	t
57	Dumbbell Stiff Leg Deadlift	{}	reps	t
63	Floor Leg Raise	{}	reps	f
72	Hanging Knee Raise	{}	reps	f
71	Rotating Mountain Climber	{}	reps	f
70	Russian Twist	{}	reps	f
69	Side Plank	{}	seconds	f
68	Hanging Leg Raise	{}	reps	f
67	Plank	{}	seconds	f
66	Cable Crunch	{}	reps	t
73	Muscle Up	{}	reps	f
77	Abdominal Rollouts	{}	reps	f
76	Abdominal Air Bike	{}	reps	f
75	Cable Hip Abduction	{}	reps	t
74	Hip Abduction Machine	{}	reps	t
81	Hanging Knee Twist Raise	{}	reps	f
80	Alternate Straight Leg Lower	{}	reps	f
79	Decline Bench Sit Up	{}	reps	f
78	Pallof Press	{}	reps	t
85	Standing Cable Crunch	{}	reps	t
84	Lying Floor Knee Tuck	{}	reps	f
83	Dead Bug	{}	reps	f
82	Pallof Press with Rotation	{}	reps	t
91	Standing Barbell Twist	{}	reps	t
90	Abominal Hip Thrust	{}	reps	f
89	Turkish Get Up	{}	reps	t
88	Wide Stance Cable Anti-Rotation	{}	reps	t
87	Standing Cable Crunch	{}	reps	t
86	Roman Chair Leg Raise	{}	reps	f
96	Standing Push Pull	{}	reps	t
95	Half Kneeling Pallof Press	{}	reps	t
94	Straight Leg Toe Touch	{}	reps	f
93	Decline Bench Leg Raise	{}	reps	f
92	Hollow Body Hold	{}	seconds	f
100	Frog Sit Up	{}	reps	f
98	Ipsilateral Bird Dog	{}	reps	f
97	Lying Alternate Heel Touches	{}	reps	f
99	L-Sit to Handstand Press	{}	reps	f
\.


--
-- TOC entry 4939 (class 0 OID 0)
-- Dependencies: 262
-- Name: blog_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: swzilina_admin
--

SELECT pg_catalog.setval('public.blog_exercises_id_seq', 1, false);


--
-- TOC entry 4786 (class 2606 OID 17122)
-- Name: blog_exercises blog_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: swzilina_admin
--

ALTER TABLE ONLY public.blog_exercises
    ADD CONSTRAINT blog_exercises_pkey PRIMARY KEY (id);


-- Completed on 2026-01-25 18:17:58

--
-- PostgreSQL database dump complete
--

