from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    # Authentication (JWT)
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),

    # API (Native App)
    path("login/", views.login, name='login_url'),
    path("get-logged-in-user/", views.get_logged_in_user, name="get_logged_in_user_url"),
    path("load-first-users/", views.load_first_users, name="load_first_users_url"),
    path("search-users/", views.search_users, name="search_users_url"),
    path("toggle-post-like/", views.toggle_post_like, name="toggle_post_like_url"),
    path("report-post/", views.report_post, name="report_post_url"),
    path("toggle-post-save/", views.toggle_post_save, name="toggle_post_save_url"),
    path("report-post-comment/", views.report_post_comment, name="report_post_comment_url"),
    path("add-comment/", views.add_comment, name="add_comment_url"),
    path("toggle-post-comment-like/", views.toggle_post_comment_like, name="toggle_post_comment_like_url"),
    path("get-processing-posts/", views.get_processing_posts, name="get_processing_posts_url"),
    path("get-chats/", views.get_chats, name="get_chats_url"),
    path("get-posts/", views.get_posts, name="get_posts_url"),
    path("get-post-comments/", views.get_post_comments, name="get_post_comments_url"),
    path("edit-post-settings/", views.edit_post_settings, name="edit_post_settings_url"),
    path("delete-post/", views.delete_post, name="delete_post_url"),
    path("delete-post-comment/", views.delete_post_comment, name="delete_post_comment_url"),
    path("toggle-follow/", views.toggle_follow, name="toggle_follow_url"),
    path("upload-post/", views.upload_post, name="upload_post_url"),
    path("get-upload-progress/<str:task_id>/", views.get_upload_progress, name="get_upload_progress_url"),
    path("register/", views.register, name="register_url"),
    path("mark-post-as-seen/", views.mark_post_as_seen, name="mark_post_as_seen_url"),
    path("tag-user/", views.tag_user, name="tag_user_url"),
    path("get-activity/", views.get_activity, name="get_activity_url"),
    path("get-weekly-activity/", views.get_weekly_activity, name="get_weekly_activity_url"),
    path("get-training-plans/", views.get_training_plans, name="get_training_plans_url"),
    path("get-official-tasks/", views.get_official_tasks, name="get_official_tasks_url"),
    path("get-custom-tasks/", views.get_custom_tasks, name="get_custom_tasks_url"),
    path("get-activity-history/", views.get_activity_history, name="get_activity_history_url"),
    path("get-xp-boost/", views.get_xp_boost, name="get_xp_boost_url"),
    path("use-xp-boost/", views.use_xp_boost, name="use_xp_boost_url"),
    path("complete-official-task/", views.complete_official_task, name="complete_official_task_url"),
    path("add-custom-task/", views.add_custom_task, name="add_custom_task_url"),
    path("toggle-complete-custom-task/", views.toggle_complete_custom_task, name="toggle_complete_custom_task_url"),
    path("delete-custom-task/", views.delete_custom_task, name="delete_custom_task_url"),
    path("delete-completed-custom-tasks/", views.delete_completed_custom_tasks, name="delete_completed_custom_tasks_url"),
    path("change-custom-tasks-order/", views.change_custom_tasks_order, name="change_custom_tasks_order_url"),
    path("new-activity/", views.new_activity, name="new_activity_url"),
    path("update-video-watch-time/", views.update_video_watch_time, name="update_video_watch_time_url"),
    path("stream-video/", views.stream_video, name="stream_video_url"),
    path("get-exercises/", views.get_exercises, name="get_exercises_url"),
    path("manage-training-plan/", views.manage_training_plan, name="manage_training_plan_url"),
    path("get-profile/<str:username>/", views.get_profile, name="get_profile_url"),
    path("remove-follower/", views.remove_follower, name="remove_follower_url"),
    path("password-reset/", views.password_reset, name="password_reset_url"),
    path("approve-follow-request/", views.approve_follow_request, name="approve_follow_request_url"),
    path("reject-follow-request/", views.reject_follow_request, name="reject_follow_request_url"),
    path("edit-account/", views.edit_account, name="edit_account_url"),
    path("report-user/", views.report_user, name="report_user_url"),
    path("suspend-user/", views.suspend_user, name="suspend_user_url"),
    path("get-chat/<str:username>/", views.get_chat, name="get_chat_url"),
    path("get-articles/", views.get_articles, name="get_articles_url"),
    path("add-article_rating/", views.add_article_rating, name="add_article_rating_url"),
    path("report-article-comment/", views.report_article_comment, name="report_article_comment_url"),
    path("add-article-comment/", views.add_article_comment, name="add_article_comment_url"),
    path("toggle-article-comment-like/", views.toggle_article_comment_like, name="toggle_article_comment_like_url"),
    path("delete-article-comment/", views.delete_article_comment, name="delete_article_comment_url"),
    path("get-article/", views.get_article, name="get_article_url"),
]
